app/controllers/usuario_controller.py
from sqlalchemy.exc import SQLAlchemyError
from flask import request, Blueprint, jsonify, render_template
import services.usuario_service as usuario_service
from exceptions.mail_invalido import mail_invalido
from exceptions.mail_eliminado import mail_eliminado
from exceptions.dni_eliminado import dni_eliminado
from exceptions.dni_invalido import dni_invalido
from exceptions.contrasenia_actual_incorrecta import contrasenia_actual_incorrecta
from exceptions.envio_mail_error import envio_mail_error
from exceptions.validacion_error import validacion_error
import utils.manejador_sesion as manejador_sesion

USUARIO_BP = Blueprint('Usuario', __name__, url_prefix='/usuario')

# Endpoint para dar de alta a un usuario
@USUARIO_BP.route("/alta", methods=["POST"])
def alta_usuario():
    try:
        datos_usuario = request.get_json()
        usuario_service.alta_usuario(datos_usuario)
        
        return jsonify({'Mensaje': 'Usuario creado con exito.'}), 201 
    
    except mail_invalido as e:
        return jsonify({'Mail-Invalido': str(e), 'Code': "MAIL-INVALIDO"}), 400 # Mensaje final de error. Para que el FE sepa que hubo un error en el BE.
    except dni_invalido as e:
        return jsonify({'Dni-Invalido': str(e), 'Code': "DNI-INVALIDO"}), 400 # Mensaje final de error. Para que el FE sepa que hubo un error en el BE.
    except SQLAlchemyError as e:
        return jsonify({'DatabaseError': str(e), 'Code': "DATABASE-ERROR"}), 500 # Mensaje final de error. Para que el FE sepa que hubo un error en el BE.
    except envio_mail_error as e: 
        return jsonify({'Envio-Mail-Error': str(e), 'Code': "ENVIO-MAIL-ERROR"}), 502 # Mensaje final de error. Para que el FE sepa que hubo un error en el BE.
    except mail_eliminado as e: 
        return jsonify({'Mail-Eliminado-Error': str(e), 'Code': "MAIL-ELIMINADO-ERROR"}), 501 # Mensaje final de error. Para que el FE sepa que hubo un error en el BE.
    except dni_eliminado as e: 
        return jsonify({'Mail-Eliminado-Error': str(e), 'Code': "DNI-ELIMINADO-ERROR"}), 501 # Mensaje final de error. Para que el FE sepa que hubo un error en el BE.
    except Exception as e:
        return jsonify({'Error': str(e), 'Code': "GENERIC-ERROR"}), 500 # Mensaje final de error. Para que el FE sepa que hubo un error en el BE.
    


@USUARIO_BP.route("/getall", methods=["GET"])
def obtener_usuarios():
    """
        Endpoint para obtener todos los usuario de la BD
    """
    try:
        usuarios = usuario_service.obtener_usuarios() # Le pasa la pelota a la funcion del service.
        respuesta = {}
        if usuarios is not None:
            respuesta = [usuario.serialize() for usuario in usuarios] # Le da formato json a la respuesta que se obtuvo.
        return jsonify(respuesta), 200 # Mensaje final de exito. Para que el FE sepa que se completó la tarea en el BE.
    
    except SQLAlchemyError as e:
        return jsonify({'DatabaseError': str(e), 'Code': "DATABASE-ERROR"}), 500 # Mensaje final de error. Para que el FE sepa que hubo un error en el BE.
    except Exception as e:
        return jsonify({'Error': str(e), 'Code': "GENERIC-ERROR"}), 500 # Mensaje final de error. Para que el FE sepa que hubo un error en el BE.


@USUARIO_BP.route("/get", methods=["GET"])
def obtener_un_solo_usuario():
    """
        Endpoint para obtener un usuario específico
    """
    try:
        mail = request.args.get('mail') 
        usuario = usuario_service.obtener_un_solo_usuario(mail) 
        respuesta = {}
        if usuario is not None:
            respuesta = usuario.serialize() 
        return jsonify(respuesta), 200 

    except SQLAlchemyError as e:
        return jsonify({'DatabaseError': str(e), 'Code': "DATABASE-ERROR"}), 500  
    except Exception as e:
       return jsonify({'Error': str(e), 'Code': "GENERIC-ERROR"}), 500 
   
   
# Endpoint para enviar correo 2fa
@USUARIO_BP.route("/enviar_correo_2fa", methods=["POST"])
def enviar_correo_2fa():
    try:
        data_2fa = request.get_json()
        print('-------------------------------------- data_2fa:', data_2fa)
        usuario_service.enviar_mail_2fa(data_2fa["mail"], data_2fa["codigo"])
        return jsonify({'Mensaje': 'Mensaje enviado.'}), 201
    except mail_invalido as e:
        print("Error en el mail 2fa: ", e)
        return jsonify({'Mail-Invalido': str(e), 'Code': "MAIL-INVALIDO"}), 400
    except SQLAlchemyError as e:
        print("Error en el sql 2fa: ", e)
        return jsonify({'DatabaseError': str(e), 'Code': "DATABASE-ERROR"}), 500
    except Exception as e:
        print("Error general 2fa: ", e)
        return jsonify({'Error': str(e), 'Code': "GENERIC-ERROR"}), 500


@USUARIO_BP.route("/iniciar_sesion", methods=["GET"])
def iniciar_sesion():
    """
        Endpoint para manejar el inicio de sesion de un usuario
    """
    try:
        mail = request.args.get('mail')
        contrasenia = request.args.get('contrasenia')
        usuario = usuario_service.iniciar_sesion(mail, contrasenia)
        if usuario:
            manejador_sesion.iniciar_sesion(usuario['id_usuario'], usuario['rol'])
            return jsonify({'Usuario': usuario, 'validacion': True}), 200
        else:
            return jsonify({'Usuario': None, 'validacion': False}), 200
        
    except mail_invalido as e:
        return jsonify({'ValueError': str(e), 'Code': "MAIL-INVALIDO"}), 400  
    except validacion_error as e:
        return jsonify({'ValueError': str(e), 'Code': "VALIDACION-ERROR"}), 400  
    except SQLAlchemyError as e:
        return jsonify({'DatabaseError': str(e), 'Code': "DATABASE-ERROR"}), 500  
    except Exception as e:
       return jsonify({'Error': str(e), 'Code': "GENERIC-ERROR"}), 500
    

@USUARIO_BP.route("/cerrar_sesion", methods=["GET"])
def cerrar_sesion():
    """
        Endpoint para manejar el cierre de sesion de un usuario
    """
    try:
        manejador_sesion.limpiar_sesion()
        return jsonify({}), 200 
    except Exception as e:
       return jsonify({'Error': str(e), 'Code': "GENERIC-ERROR"}), 500 


@USUARIO_BP.route("/cambiar_rol", methods=["POST"])
def cambiar_rol():
    """
        Endpoint para cambiar el rol de un usuario empleado o gerente.
    """
    try:
        usuario_mail = request.args.get('mail')
        usuario_service.cambiar_rol_usuario(usuario_mail)
        return jsonify({}), 200
    
    except mail_invalido as e:
        return jsonify({'ValueError': str(e), 'Code': "MAIL-INVALIDO"}), 400  
    except Exception as e:
       return jsonify({'Error': str(e), 'Code': "GENERIC-ERROR"}), 500 

    
# Endpoint que obtiene todos los empleados y los gerentes: Listar Personal
@USUARIO_BP.route("/getEmpleadosGerentes", methods=["GET"]) 
def obtener_usuarios_empleados_y_gerentes():
    empleados = usuario_service.listar_personal()

    sesion_actual = manejador_sesion.ver_sesion_actual()
    usuario_actual = usuario_service.obtener_un_solo_usuario_por_ID(sesion_actual["id_usuario"])
    print(usuario_actual)
    mail_usuario_actual = usuario_actual.mail

    return render_template("listado_empleados.html",empleados = empleados, mail_usuario_actual = mail_usuario_actual)

@USUARIO_BP.route('/tabla_empleados')
def tabla_empleados():
    empleados = usuario_service.listar_personal()  # tu lógica para obtener los empleados

    sesion_actual = manejador_sesion.ver_sesion_actual()
    usuario_actual = usuario_service.obtener_un_solo_usuario_por_ID(sesion_actual["id_usuario"])
    print(usuario_actual)
    mail_usuario_actual = usuario_actual.mail

    return render_template('tabla_empleados.html', empleados = empleados, mail_usuario_actual = mail_usuario_actual)

@USUARIO_BP.route('/get_lista_inquilinos')
def tabla_inquilinos():
    # inquilinos = usuario_service.listar_inquilinos() 
    dni = request.args.get('dni')
    if dni:
        inquilinos = usuario_service.buscar_inquilinos_por_dni(dni)
    else:
        inquilinos = usuario_service.listar_inquilinos() 
    return render_template('listado_inquilinos.html', inquilinos=inquilinos)

# Endpoint que elimina logicamente un usuario con mail especifico.
@USUARIO_BP.route("/eliminar", methods=["DELETE"])
def eliminar_usuario():
    try:
        mail = request.args.get('mail') # Obtiene el dato que se pasa como parametro.
        usuario_service.eliminar_usuario(mail) # Le pasa la pelota a la funcion del service.
        return jsonify({'Mensaje': 'Usuario eliminado con exito.'}), 200 # Mensaje final de exito. Para que el FE sepa que se completó la tarea en el BE.
    
    except SQLAlchemyError as e:
        return jsonify({'DatabaseError': str(e)}), 500 # Mensaje final de error. Para que el FE sepa que hubo un error en el BE.    
    except ValueError as e:
        return jsonify({'ValueError': str(e)}), 400 # Mensaje final de error. Para que el FE sepa que hubo un error en el BE.
    except Exception as e:
        return jsonify({'Error': str(e)}), 500 # Mensaje final de error. Para que el FE sepa que hubo un error en el BE.


@USUARIO_BP.route("/modificar", methods=["PUT"])
def modificar_usuario():
    try:
        id_usuario = request.args.get('id_usuario') # Obtiene el dato que se pasa como parametro.
        datos_actualizados = request.get_json() # Obtiene el objeto en formato json que se pasa como parametro.
        usuario_service.modificar_usuario(id_usuario, datos_actualizados) # Le pasa la pelota a la funcion del service.
        return jsonify({'Mensaje': 'Usuario modificado con exito.'}), 200 # Mensaje final de exito. Para que el FE sepa que se completó la tarea en el BE.

    except SQLAlchemyError as e:
        return jsonify({'DatabaseError': str(e), 'Code': "DATABASE-ERROR"}), 500 # Mensaje final de error. Para que el FE sepa que hubo un error en el BE.
    except ValueError as e:
        return jsonify({'ValueError': str(e), 'Code': "ID-INEXISTENTE"}), 400 # Mensaje final de error. Para que el FE sepa que hubo un error en el BE.
    except Exception as e:

app/templates/2fa.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Alquiler Express</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/2fa.css') }}"
    />
  </head>
  <body>
    
    <div id="toast-container"></div>
    <div class='content2FA' id='content2FA'>

      <div class='padre2fa'>

      <form action="/verificar-codigo" method="POST" id='codigo2FA'>
        <div class="pup2FA" id='pup2FA'>
          <div class="close">
            <a id='a-close' href="{{ url_for('Usuario.iniciar_sesion') }}">
              <img src="{{ url_for('static', filename='img/close.png') }}" alt="" />
            </a>
          </div>
          <h1>(2FA)</h1>
          <h2>Por favor, ingrese el código de confirmación que fue enviado al mail</h2>
          <div class="divInputConfirmation" id='ipt-confirmation'>
            <input type="number" name="digit1" required />
            <input type="number" name="digit2" required />
            <input type="number" name="digit3" required />
            <input type="number" name="digit4" required />
            <input type="number" name="digit5" required />
            <input type="number" name="digit6" required />
          </div>
          <button type='button' id='btn-reenviar-cod'>Reenviar código</button>
        </div>
      </form>
      </div>
      <script>const urlIndex = "{{ url_for('index') }}";</script>
      <script src="{{ url_for('static', filename='js/2fa.js') }}"></script>
    </div>

  </body>
</html>

app/templates/base_gerente.html
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="icon" href="{{ url_for('static', filename='img/logo.png') }}" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"/>
  <title>Alquiler Express</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" />
  <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}" />
  <link href="https://cdn.jsdelivr.net/npm/litepicker/dist/css/litepicker.css" rel="stylesheet" />
  
</head>
<body>

  
  <div class="sidebar" id="sidebar" >
    <button id="btnToggleSidebar" class="sidebar-toggle collapsed">
      <span class="icon">&lt;&lt;</span>
      <span class="label"></span>
    </button>
<div class="sidebar-content">
    <h5 class="filter-title mt-4">Filtrar Resultados</h5>

    <label class="filter-title mt-3">Precio por dia ($)</label>
    <input type="range" class="form-range" min="10000" max="300000" step="10000" id="precioRange" />
    <div id="precioLabel">Hasta $3000000</div>

    <label class="filter-title mt-3">Tipo de propiedad</label>
    <select class="form-select" id="tipoVivienda">
    <option value="">Todos</option>
    <option value="hotel">Hotel</option>
    <option value="ph">PH</option>
    <option value="departamento">Departamento</option>
    <option value="casa">Casa</option>
    <option value="quinta">Quinta</option>
    <option value="hostel">Hostel</option>
    </select>
    
    <label class="filter-title mt-3">Cantidad de habitaciones</label>
    <select class="form-select" id="cantidadHabitaciones">
      <option value="">Seleccionar</option>
      <option>1</option>
      <option>2</option>
      <option>3</option>
      <option>4</option>
      <option>5</option>
      <option>6</option>
      <option>7</option>
    </select>

    <!-- <label class="filter-title mt-3">Metros cuadrados (mínimo)</label>
    <input type="number" class="form-control" id="metrosCuadrados" placeholder="Ej: 20" /> -->

    <button class="btn btn-success btn-filtros mt-4" id="aplicarFiltros">Aplicar Filtros</button>
    <button class="btn btn-secondary btn-filtros mt-2" id="quitarFiltros">Quitar Filtros</button>
  </div>
</div>

  <div class="logo-custom py-4">
    <div class="ver-perfil-container">
      <div>
        <div class="bienvenida-usuario d-flex justify-content-between align-items-center">
          <span><b id="tipo-usuario"></b></span>
          <div class="grupo-derecha d-flex align-items-center">
            <span class="border-end pe-2"><b id="nombre-apellido-usuario"></b></span>
            <button type="button" class="btn btn-primary ms-2" id="btn-ver-perfil">
              <i class="fa-solid fa-user"></i>
            Ver perfil
          </button>
        </div>
      </div>
    </div>
    <p></p>

  <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light navbar-custom px-4 w-100">    
      <div class="d-flex align-items-center me-auto gap-3">
        <button type="button" class="btn btn-cerrar-sesion" id="btn-cerrar-sesion">Cerrar Sesión</button>
      </div>
      <!-- Enlaces a la izquierda -->
      <div class="d-flex align-items-center me-auto gap-3">
        <a href="{{ url_for('registro') }}" class="btn btn-registrarse" id="reg_inq">Registrar Inquilino</a>
        <!-- <a href="#" class="btn btn-ingresar">Listar inquilinos</a> -->
      </div>

      <div class="d-flex align-items-center me-auto gap-3">
        <a href="{{url_for('altaEmpleado')}}" class="btn btn-registrarse">Registrar Empleado</a>
        <a href="/usuario/getEmpleadosGerentes" class="btn btn-ingresar">Listar Personal</a>
      </div>

      
      <div class="d-flex align-items-center me-auto gap-3">
        <a href="{{url_for('registro_propiedad')}}" class="btn btn-registrarse">Registrar Propiedad</a>
        <a href="/propiedad/getPropiedades" class="btn btn-ingresar">Listar Propiedades</a>
        <a href="/reserva/getReservas" class="btn btn-registrarse" id="btn-ver-alquileres">Listar Reservas</a>
      
      </div>


      <div class="d-flex align-items-center me-auto gap-3">
        <a href="{{url_for('generar_estadisticas')}}" class="btn btn-registrarse">Generar Estadísticas</a>      
      </div>
  
  
    </nav>

    <div class="row g-2 align-items-center">
      <div class="col-md-2 text-center">
        <a href="{{ url_for('inicio') }}">
          <img src="{{ url_for('static', filename='img/logo.png') }}" alt="Logo" width="100" height="100" class="img-fluid">
        </a>
      </div>
      <div class="col-md-10">
        <form class="row g-2 form" id="searchForm">
          <div class="col-md-4">
            <input type="text" class="form-control input-custom" id="localidad"  placeholder="¿A dónde vas?"  required/>
            <span class="error-msg" id="error-localidad"></span>
          </div>
          <div class="col-md-3">
            <input type="number" min="1" max="10" class="form-control input-custom" id="huespedes" placeholder="¿Cuántos huéspedes?"  required/>
            <span class="error-msg" id="error-huespedes"></span>
          </div>
           <!-- NUEVOS CAMPOS DE FECHA -->
          <div class="col-md-2">
            <input id="checkin" placeholder="Check-in" readonly class="form-control input-custom" id="checkin" required/>
            <span class="error-msg" id="error-checkin"></span>
          </div>
          <div class="col-md-2">
            <input id="checkout" placeholder="Check-out" readonly class="form-control input-custom" id="checkout" required/>
            <span class="error-msg" id="error-checkout"></span>
          </div>
          <div class="btn-container col-md-2">
            <button type="submit" class="btn btn-buscar btn btn-warning w-100" id="btnBuscar"> <i class="fas fa-search"></i></button>
          </div>
        </form>
      </div>
    </div>
  </div>

  <!-- Modal Medios de Pago -->
  <div class="modal fade" id="mediosPagoModal" tabindex="-1" aria-labelledby="mediosPagoModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="mediosPagoModalLabel">Medios de Pago</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
        </div>
        <div class="modal-body">
          💳 Tarjeta de Débito<br />
          💳 Tarjeta de Crédito<br />
          💰 Mercado Pago<br />
          💵 Efectivo
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
        </div>
      </div>
    </div>
  </div>

  <!-- Modal Contacto -->
  <div class="modal fade" id="contactoModal" tabindex="-1" aria-labelledby="contactoModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="contactoModalLabel">Contacto</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
        </div>
        <div class="modal-body">
          📞 Teléfono: 123456<br />
          📧 Mail: alquilerexpress@gmail.com
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
        </div>
      </div>
    </div>
  </div>

    <!-- Modal Cerrar Sesion -->
  <div class="modal fade" id="cerrarSesionModal" tabindex="-1" aria-labelledby="cerrarSesionModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="cerrarSesionModalLabel">Cerrar Sesión</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
        </div>
        <div class="modal-body">
          ¿Desea cerrar la sesión actual?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" id="btn-confirmacion-cerrar-sesion" data-bs-dismiss="modal">Aceptar</button>
        </div>
      </div>
    </div>
  </div>
      <!-- Modal Gestion de Alquileres -->
  <div class="modal fade" id="gestionAlquileresModal" tabindex="-1" aria-labelledby="gestionAlquileresModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="gestionAlquileresModalLabel">Gestion de alquileres</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
        </div>
        <div class="modal-body">
            <button class="btn btn-registrarse inside-modal-btn" id="btn-buscar-reserva">Buscar Reserva</button>
            <button class="btn btn-ingresar inside-modal-btn"  id="btn-listar-reservas">Listar Reserva</button><br>
            <button class="btn btn-registrarse inside-modal-btn"  id="o">Realizar alquiler para inquilino</button><br>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
        </div>
      </div>
    </div>
  </div>


  <!-- Contenedor de propiedades -->
  <div class="container my-5">
    <h3 class="mb-3" id="titulo"></h3>
    <div class="row" id="propiedades">
    <section class="d-flex justify-content-center align-items-center" style="min-height: 500px; margin-top: 2px;">
      <div class="card text-white border border-dark shadow" style="width: 900px; max-width: 100%;">
        <img src="/static/img/BA.jpg" class="card-img" alt="Vista de ciudad" style="height: 400px; object-fit: cover;">
        <div class="card-img-overlay d-flex flex-column justify-content-center text-center bg-dark bg-opacity-50">
          <h2 class="card-title fw-bold display-5">Tu próximo hogar te espera</h2>
          <p class="card-text fs-4">Explorá alquileres en las mejores zonas de la ciudad</p>
        </div>
      </div>
    </section>
    </div>
  </div>
  
  <!-- Modal de propiedades -->
<!-- <div class="modal fade" id="propiedadModal" tabindex="-1" aria-labelledby="propiedadModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="propiedadModalLabel">Detalles de la Propiedad</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" id="modal-body-content">
        </div>
    </div>
  </div>
</div> -->


  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/litepicker/dist/litepicker.js"></script>
  <script src="{{ url_for('static', filename='js/base.js') }}"></script>


</body>
</html>

app/templates/iniciar_sesion.html
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Iniciar Sesión</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/iniciar_sesion.css') }}">
</head>
<body>

  <div class="logo-custom py-4">
    <!-- Navbar --> 
    <div class="row g-2 align-items-center">
      <div class="col-md-2 text-center">
        <a href="{{ url_for('inicio') }}">
          <img src="{{ url_for('static', filename='img/logo.png') }}" alt="Logo" width="100" height="100" class="img-fluid">
        </a>
      </div>
    </div>
  </div>
  

  <div class="d-flex justify-content-center align-items-center">
    <div class="container" style="max-width: 500px;">

      <div class="row mb-3 text-center">
        <h1 class="titulo-principal">Iniciar Sesión</h1>
      </div>

      <form id="formIngresar">
        <div class="mb-3">
          <label for="mail" class="form-label">Mail<span class="asterisco-obligatorio">*</span></label>
          <input type="text" class="form-control" id="mail" maxlength="50" required>
          <span class="error-msg" id="error-mail"></span>
        </div>
        <div class="mb-3">
          <label for="contrasenia" class="form-label">Contraseña<span class="asterisco-obligatorio">*</span></label>
          <input type="password" class="form-control" id="contrasenia" required>
          <span class="error-msg" id="error-contrasenia"></span>
        </div>

        <div class="d-flex justify-content-center align-items-center gap-3 mt-4">
          <button type="submit" class="btn btn-primary" id="btnIngresar">Ingresar</button>
          <button type="button" class="btn btn-secondary" id="btnRegistrarse">Registrarse</button>
        </div>
        <div class="row mb-3 text-center">
          <span class="asterisco-obligatorio">* Campos obligatorios</span>
        </div>
      </div>
      </form>

    </div>
  </div>


  <div id="toast-container"></div>
  <div class='content2FA' id='content2FA'>
    <div class='padre2fa'>
    <form action="/verificar-codigo" method="POST" id='codigo2FA'>
      <div class="pup2FA" id='pup2FA'>
        <div class="close">
          <a id='a-close' href="{{ url_for('iniciar_sesion') }}">
            <img src="{{ url_for('static', filename='img/close.png') }}" alt="" />
          </a>
        </div>
        <h1>(2FA)</h1>
        <h2>Por favor, ingrese el código de confirmación que fue enviado al mail</h2>
        <div class="divInputConfirmation" id='ipt-confirmation'>
          <input type="number" name="digit1" required />
          <input type="number" name="digit2" required />
          <input type="number" name="digit3" required />
          <input type="number" name="digit4" required />
          <input type="number" name="digit5" required />
          <input type="number" name="digit6" required />
        </div>
        <button type='button' id='btn-reenviar-cod'>Reenviar código</button>
      </div>
    </form>
    </div>
  </div>


  <script src="{{ url_for('static', filename='js/iniciar_sesion.js') }}"></script>
</body>
</html>

app/templates/medios_de_pago_inquilino.html
<strong>Medio de pago</strong>
<div class="form-check">
    <label class="form-check-label">A través de Mercado Pago con:</label>
    <p></p>
    <label class="form-check-label"> - Transferencia</label>
    <label class="form-check-label"> - Tarjeta de Crédito/Débito</label>
    <p></p>

</div>